### ISSUE TITLE
Bump runtime to 24.08

### ISSUE THREAD

**Issue by farribeiro** [flathub/br.gov.fazenda.receita.irpf2024#15]
Hi.

Runtime version 24.08 is now available for use.

I hope this issue helps keep it up to date. 

Fábio

**Comment by farribeiro** [comment]
Fixed a typo in the title

**Comment by guihkx** [comment]
This depends on https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/pull/71 getting merged first.
